title: Progressive and Multi-modal Vehicle Re-identification for Large-scale Urban Surveillance
#description: This is the project page for VeRi dataset which is a large scale image dataset for vehicle re-identification in urban traffic surveillance.
author: Xinchen Liu
theme: jekyll-theme-cayman
